name: bootstrap_like_grid
description: A grid system similar to bootstrap with minimal functionality
version: 1.0.0
repository: https://github.com/Honeyman-Applications/bootstrap_like_grid

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

